version: "3.3"

services:
  app:
    depends_on:
      - redis
    container_name: app_outvio
    # restart: unless-stopped
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ".:/app"
    networks:
      - app-tier

  redis:
    container_name: "redis"
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge